export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_FULL_CALENDAR_JS_APPOINTMENTS = 'GET_FULL_CALENDAR_JS_APPOINTMENTS';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';